## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [11]:
import numpy as np
arr = np.linspace(-1.3, 2.5, 65)
print(arr)

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [12]:
n = int(input())
print(np.array([1, 2, 3] * n))

5
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [13]:
print(np.arange(1, 20, 2))

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [14]:
arr = np.ones((10, 10))
arr[1:9, 1:9] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [15]:
arr = np.zeros((8, 8))
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [16]:
def make_answer(n):
    a = np.ones((n,n)) * np.linspace(0, n - 1, n)
    b = a.transpose()
    return a + b
n = int(input())
print(make_answer(n))

5
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [17]:
vector = np.linspace(0, 5, 5)
matrix = np.ones((5,5)) * np.linspace(5, 9, 5)
print(vector)
print()
print(matrix)
print()
print(np.dot(vector, vector))
print()
print(np.dot(matrix, vector))
print()
print(np.dot(matrix, matrix))

[0.   1.25 2.5  3.75 5.  ]

[[5. 6. 7. 8. 9.]
 [5. 6. 7. 8. 9.]
 [5. 6. 7. 8. 9.]
 [5. 6. 7. 8. 9.]
 [5. 6. 7. 8. 9.]]

46.875

[100. 100. 100. 100. 100.]

[[175. 210. 245. 280. 315.]
 [175. 210. 245. 280. 315.]
 [175. 210. 245. 280. 315.]
 [175. 210. 245. 280. 315.]
 [175. 210. 245. 280. 315.]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [18]:
arr_sin = np.sin(np.arange(0, 1.01, 0.05))
arr_cos = np.cos(np.arange(0, 1.01, 0.05))
answer = np.hstack((arr_cos, arr_sin))
print(answer)

[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231 0.         0.04997917 0.09983342
 0.14943813 0.19866933 0.24740396 0.29552021 0.34289781 0.38941834
 0.43496553 0.47942554 0.52268723 0.56464247 0.60518641 0.64421769
 0.68163876 0.71735609 0.75128041 0.78332691 0.8134155  0.84147098]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [19]:
A = np.random.rand(3, 5) * 4 - 1
print(A)

[[ 2.48346445  1.90714519 -0.97473559 -0.21141753  1.52433311]
 [ 0.7003805  -0.2072258   0.55226602  2.67017167  2.27201919]
 [ 0.6749388   1.53875927 -0.17768055  1.8458741   0.08491927]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [20]:
sum_all = np.sum(A)
print(sum_all, "\n")

sum_i = np.sum(A, axis=1)
print(sum_i, "\n")

sum_j = np.sum(A, axis=0)
print(sum_j, "\n")

mean_i = np.mean(A, axis=1)
print(mean_i, "\n")

var_i = np.var(A, axis=1)
print(var_i, "\n")

std_i = np.std(A, axis=1)
print(std_i, "\n")

14.683212102705792 

[4.72878963 5.98761158 3.9668109 ] 

[ 3.85878375  3.23867866 -0.60015011  4.30462824  3.88127157] 

[0.94575793 1.19752232 0.79336218] 

[1.73018129 1.19201252 0.62444752] 

[1.31536356 1.09179326 0.79021992] 



11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [21]:
A = ((A.transpose() - mean_i) / std_i).transpose()
A

array([[ 1.16903537,  0.73089091, -1.46004768, -0.87973812,  0.43985952],
       [-0.45534428, -1.28664296, -0.59100593,  1.34883536,  0.98415782],
       [-0.14986129,  0.94327803, -1.22882593,  1.33192279, -0.89651361]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [22]:
a = A[::, 2]
print(a, "\n")
b = np.argsort(a, axis=0)
print(b, "\n")
A = A[b]
print(A)

[-1.46004768 -0.59100593 -1.22882593] 

[0 2 1] 

[[ 1.16903537  0.73089091 -1.46004768 -0.87973812  0.43985952]
 [-0.14986129  0.94327803 -1.22882593  1.33192279 -0.89651361]
 [-0.45534428 -1.28664296 -0.59100593  1.34883536  0.98415782]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [23]:
A_trans = np.transpose(A)
print(A_trans, "\n")
B = np.dot(A_trans, A)
C = np.dot(A, A_trans)
print(B, "\n\n", C)

[[ 1.16903537 -0.14986129 -0.45534428]
 [ 0.73089091  0.94327803 -1.28664296]
 [-1.46004768 -1.22882593 -0.59100593]
 [-0.87973812  1.33192279  1.34883536]
 [ 0.43985952 -0.89651361  0.98415782]] 

[[ 1.59644052  1.29894198 -1.25358277 -1.84223312  0.20043339]
 [ 1.29894198  3.07942509 -1.46584646 -1.12208861 -1.790432  ]
 [-1.25358277 -1.46584646  3.99104042 -1.14941137 -0.12219982]
 [-1.84223312 -1.12208861 -1.14941137  4.36731432 -0.25358122]
 [ 0.20043339 -1.790432   -0.12219982 -0.25358122  1.96577966]] 

 [[ 5.          0.74230135 -1.36354307]
 [ 0.74230135  5.          0.49505354]
 [-1.36354307  0.49505354  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [24]:
np.sum(B * np.eye(5)) + np.sum(C * np.eye(3))

30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [25]:
print(A, "\n\n", B, "\n\n", C, "\n")
print("Детерминанты: A = нельзя найти, так как A не квадратная", ", B =", np.linalg.det(B), ", C =", np.linalg.det(C), "\n")
print("Ранги: A =", np.linalg.linalg.matrix_rank(A), ", B =", np.linalg.linalg.matrix_rank(B), ", C =", np.linalg.linalg.matrix_rank(C), "\n")
print("Спектры: B =", np.linalg.eigvals(B), ", C =", np.linalg.eigvals(C))

[[ 1.16903537  0.73089091 -1.46004768 -0.87973812  0.43985952]
 [-0.14986129  0.94327803 -1.22882593  1.33192279 -0.89651361]
 [-0.45534428 -1.28664296 -0.59100593  1.34883536  0.98415782]] 

 [[ 1.59644052  1.29894198 -1.25358277 -1.84223312  0.20043339]
 [ 1.29894198  3.07942509 -1.46584646 -1.12208861 -1.790432  ]
 [-1.25358277 -1.46584646  3.99104042 -1.14941137 -0.12219982]
 [-1.84223312 -1.12208861 -1.14941137  4.36731432 -0.25358122]
 [ 0.20043339 -1.790432   -0.12219982 -0.25358122  1.96577966]] 

 [[ 5.          0.74230135 -1.36354307]
 [ 0.74230135  5.          0.49505354]
 [-1.36354307  0.49505354  5.        ]] 

Детерминанты: A = нельзя найти, так как A не квадратная , B = 4.234268926886637e-30 , C = 110.72115839539953 

Ранги: A = 3 , B = 3 , C = 3 

Спектры: B = [ 3.20715094e+00  6.39100331e+00  5.40184575e+00 -4.63148454e-16
  4.81204910e-16] , C = [3.20715094 6.39100331 5.40184575]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [26]:
def count_rectangular_method(delta_x, x):
    return delta_x * sum(f(x))
def count_trapezoid_method(delta_x, x):
    return delta_x / 2 * (f(x[0]) + 2 * sum(f(x[1:-1])) + f(x[-1]))
def count_simpson_method(delta_x, x):
    return delta_x / 3 * (f(x[0]) + 2 * sum(f(x[2:-1:2])) + 4 * sum(f(x[1:-1:2])) + f(x[-1]))

In [27]:
def get_variant(my_seed):
    np.random.seed(my_seed)
    return np.random.randint(9)
def f(x):
    return (np.e ** (1 / (x ** 2))) / x ** 3
variant = get_variant(1032201717)
print("Мой вариант =", variant)
greh = 0.00001
correct = 0.717128205886
start = 1
end = 2.00000001
print("Точный ответ =", correct)
use_rectangular_method()
use_trapezoid_method()
use_simpson_method()

Мой вариант = 2
Точный ответ = 0.717128205886
Количество итераций метода прямоугольников для 2 варианта = 6 . Ответ =  0.7171296453250654
Количество итераций метода трапеций для 2 варианта = 3 . Ответ =  0.7171293150953367
Количество итераций метода трапеций для 2 варианта = 2 . Ответ =  0.7171282495037866


In [28]:
def f(x):
    return 1 / (np.sqrt(2 + 3 * x - 2 * x ** 2))
variant = 9
print("My variant:", variant)
correct = 1.11072073454
end_array = [1.8, 1.99, 2 - 0.00000000000001]
delta_array = [0.000001, 0.0000001, 0.000000001]
print("Точный ответ =", correct)
use_rectangular_method_9()
use_trapezoid_method_9()
use_simpson_method_9()

My variant: 9
Точный ответ = 1.11072073454
Погрешность метода прямоугольников для 9 варианта = 9.974242836330305e-06 . Ответ =  1.1107307087828364
Погрешность метода трапеции для 9 варианта = 8.12868665800437e-06 . Ответ =  1.110712605853342
Погрешность метода Симпсона для 9 варианта = 1.687887753210049e-05 . Ответ =  1.110703855662468


In [29]:
def use_rectangular_method():
    delta = 0.1
    x_array = np.arange(start, end, delta)
    rectangular_method = count_rectangular_method(delta, x_array)
    n = 1
    while abs(correct - rectangular_method) > greh:
        delta /= 10
        x_array = np.arange(start, end, delta)
        rectangular_method = count_rectangular_method(delta, x_array)
        n += 1
    print("Количество итераций метода прямоугольников для", variant, "варианта =",n, ". Ответ = ", rectangular_method)

def use_trapezoid_method():
    delta = 0.1
    x_array = np.arange(start, end, delta)
    trapezoid_method = count_trapezoid_method(delta, x_array)
    n = 1
    while abs(correct - trapezoid_method) > greh:
        delta /= 10
        x_array = np.arange(start, end, delta)
        trapezoid_method = count_trapezoid_method(delta, x_array)
        n += 1
    print("Количество итераций метода трапеций для", variant, "варианта =",n, ". Ответ = ", trapezoid_method)

def use_simpson_method():
    delta = 0.1
    x_array = np.arange(start, end, delta)
    simpson_method = count_simpson_method(delta, x_array)
    n = 1
    while abs(correct - simpson_method) > greh:
        delta /= 10
        x_array = np.arange(start, end, delta)
        simpson_method = count_simpson_method(delta, x_array)
        n += 1
    print("Количество итераций метода трапеций для", variant, "варианта =",n, ". Ответ = ", simpson_method)

In [30]:
def use_rectangular_method_9():
    start = 3 / 4
    rectangular_method = 0
    k = 0
    while k < len(end_array):
        delta = delta_array[k]
        x_array = np.arange(start, end_array[k], delta)
        rectangular_method += count_rectangular_method(delta, x_array)
        start = end_array[k]
        k += 1
    print("Погрешность метода прямоугольников для", variant, "варианта =", abs(correct - rectangular_method), ". Ответ = ", rectangular_method)
def use_trapezoid_method_9():
    start = 3 / 4
    trapezoid_method = 0
    k = 0
    while k < len(end_array):
        delta = delta_array[k]
        x_array = np.arange(start, end_array[k], delta)
        trapezoid_method += count_trapezoid_method(delta, x_array)
        start = end_array[k]
        k += 1
    print("Погрешность метода трапеции для", variant, "варианта =", abs(correct - trapezoid_method), ". Ответ = ", trapezoid_method)
def use_simpson_method_9():
    start = 3 / 4
    simpson_method = 0
    k = 0
    while k < len(end_array):
        delta = delta_array[k]
        x_array = np.arange(start, end_array[k], delta)
        simpson_method += count_simpson_method(delta, x_array)
        start = end_array[k]
        k += 1
    print("Погрешность метода Симпсона для", variant, "варианта =", abs(correct - simpson_method), ". Ответ = ", simpson_method)
